name: deploy-kenyan-auctioneers-app-heroku  

on:
  push:
    branches:                                            
      - master
      - main

jobs:  
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v3
      
      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
          
      - name: Get pnpm store directory
        id: pnpm-cache
        run: | 
          echo "::set-output name=name=pnpm_cache_dir::$(pnpm store path)"
          
#       - uses: actions/cache@v3
#         name: Setup pnpm cache
#         with:
#           path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
#           key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
#           restore-keys: |
#             ${{ runner.os }}-pnpm-store-
            
      - name: Install dependencies
        run: pnpm install
      
      - name: Run production migration                   
        run: pnpm run migrate:deploy                           
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          
      - uses: akhileshns/heroku-deploy@v3.12.12          
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
