name: deploy-kenyan-auctioneers-app-heroku  

on:
  push:
    branches:                                            
      - master
      - main

jobs:  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Action for pnpm
        uses: znck/pnpm@v0.1.0-alpha.1  
      - run: npm i -g pnpm
      - run: pnpm install
      - name: Run production migration                   
        run: pnpm run migrate:deploy                           
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - uses: akhileshns/heroku-deploy@v3.12.12          
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
