name: deploy-kenyan-auctioneers-server-on-heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pnpm ci
      - name: Run production migration
        run: pnpm run migrate:deploy
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
      - uses: akhileshns/heroku-deploy@3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
